version: '3.1'

services:
   tsung:
     image: opsta/tsung:latest
     volumes:
       - ../xml:/root/.tsung
     restart: always
     entrypoint: "sleep 9999999"
     ports:
      - "8090:8090"
      - "8091:8091"